---

- hosts: website 
  become: true
  tasks:

  - name: install apache2 and php packages
    tags: apache,php
    package:
      name: 
        - "{{ apache_package }}" 
        - "{{ php_package }}"
      state: latest
      update_cache: yes


  - name: copy default html file for site
    tags: apache, apache2, httpd, website
    copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
