---

- hosts: all
  become: true
  tasks:

  - name: create user simone
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHvaH+PpLjdSb8/mEHFGa+3ZCkL2bOrUGTQEoupEDzQn ansible"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: website 
  become: true
  tasks:

  - name: install apache2 and php packages
    tags: apache,php
    package:
      name: 
        - "{{ apache_package }}" 
        - "{{ php_package }}"
      state: latest
      update_cache: yes


  - name: copy default html file for site
    tags: apache, apache2, httpd, website
    copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
